In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
iris = sns.load_dataset('iris')

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X=iris.drop('species',axis=1)
y=iris['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
lr  =  LogisticRegression()

In [8]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
predictions = lr.predict(X_test)
predictions[:10]

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa'],
      dtype=object)

In [11]:
y_test.head(10)

33         setosa
16         setosa
43         setosa
129     virginica
50     versicolor
123     virginica
68     versicolor
53     versicolor
146     virginica
1          setosa
Name: species, dtype: object

In [12]:
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
predall = lr.predict(X)
print(confusion_matrix(y,predall))

[[50  0  0]
 [ 0 41  9]
 [ 0  0 50]]


In [15]:
print(classification_report(y,predall))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        50
 versicolor       1.00      0.82      0.90        50
  virginica       0.85      1.00      0.92        50

avg / total       0.95      0.94      0.94       150

