In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df['3G&4G'] = [1 if i==j else 0 for i,j in zip(df['four_g'].values,df['three_g'].values)]

In [5]:
df.head().iloc[:,[11,12]]

px_height  px_width
0         20       756
1        905      1988
2       1263      1716
3       1216      1786
4       1208      1212

In [6]:
df['aspect_ratio'] = df['px_width'].divide(df['px_height'])

In [7]:
for i in enumerate(df.columns):
    print(i)

(0, 'battery_power')
(1, 'blue')
(2, 'clock_speed')
(3, 'dual_sim')
(4, 'fc')
(5, 'four_g')
(6, 'int_memory')
(7, 'm_dep')
(8, 'mobile_wt')
(9, 'n_cores')
(10, 'pc')
(11, 'px_height')
(12, 'px_width')
(13, 'ram')
(14, 'sc_h')
(15, 'sc_w')
(16, 'talk_time')
(17, 'three_g')
(18, 'touch_screen')
(19, 'wifi')
(20, 'price_range')
(21, '3G&4G')
(22, 'aspect_ratio')


In [8]:
df.iloc[1481,22] = 1050
df.iloc[1933,22] = 1050

In [9]:
X = df.iloc[:,[0,1,3,4,6,7,9,10,13,14,15,16,19,21,22]].values
y = df.iloc[:,20].values
X.shape,y.shape

((2000, 15), (2000,))

In [98]:
X.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [133]:
df[df['px_width']>1950].iloc[:,11].mean(axis=0)

1051.6081081081081

In [134]:
df[df['aspect_ratio']>100000]

Empty DataFrame
Columns: [battery_power, blue, clock_speed, dual_sim, fc, four_g, int_memory, m_dep, mobile_wt, n_cores, pc, px_height, px_width, ram, sc_h, sc_w, talk_time, three_g, touch_screen, wifi, price_range, 3G&4G, aspect_ratio]
Index: []

[0 rows x 23 columns]

In [101]:
df.iloc[1481,22] = 1081
df.iloc[1933,22] = 1081

In [135]:
from sklearn.svm import SVC

In [136]:
svc = SVC()

In [137]:
from sklearn.cross_validation import train_test_split
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,random_state=944)

In [138]:
svc.fit(Xtrain,ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [139]:
predictions = svc.predict(Xtest)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(ytest,predictions))

[[  0 130   0   0]
 [  0 112   0   0]
 [  0 119   0   0]
 [  0 139   0   0]]


In [140]:
print(classification_report(ytest,predictions))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       130
          1       0.22      1.00      0.37       112
          2       0.00      0.00      0.00       119
          3       0.00      0.00      0.00       139

avg / total       0.05      0.22      0.08       500



C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [141]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [142]:
from sklearn.model_selection import GridSearchCV

In [143]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [144]:
grid.fit(Xtrain,ytrain)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.2589641434262948, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.7s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.2589641434262948, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.25851703406813625, total=   0.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.2589641434262948, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=rbf 

[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.7334669338677354, total=   0.1s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.7354709418837675, total=   0.1s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.2589641434262948, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.2589641434262948, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.25851703406813625, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:   30.2s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [145]:
grid.best_params_

{'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}

In [146]:
grid.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [147]:
grid_predictions = grid.predict(Xtest)

In [148]:
print(confusion_matrix(ytest,grid_predictions))

[[117  13   0   0]
 [ 16  80  16   0]
 [  0  25  82  12]
 [  0   0  25 114]]


In [149]:
print(classification_report(ytest,grid_predictions))

             precision    recall  f1-score   support

          0       0.88      0.90      0.89       130
          1       0.68      0.71      0.70       112
          2       0.67      0.69      0.68       119
          3       0.90      0.82      0.86       139

avg / total       0.79      0.79      0.79       500



In [150]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_recall_fscore_support as score

In [151]:
for i in range(1,12):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(Xtrain,ytrain)
    pred = knn.predict(Xtest)
    precision,recall,fscore,support=score(ytest,pred,average='macro')
    print(i,end='\n\n')
    print('Precision:'+str(precision))
    print('Recall'+str(recall))
    print('F-score'+str(fscore))
    print('Support'+str(support))

1

Precision:0.7192026449660893
Recall0.7176375399357308
F-score0.7180311218738182
SupportNone
2

Precision:0.7669656952034001
Recall0.7625531895104473
F-score0.7601215319686452
SupportNone
3

Precision:0.7811406092953939
Recall0.7798846281733502
F-score0.7800877860747749
SupportNone
4

Precision:0.7874936587986034
Recall0.7843423741937284
F-score0.7833516886043249
SupportNone
5

Precision:0.7929548879111495
Recall0.7912027456250901
F-score0.7912957869867865
SupportNone
6

Precision:0.7864964985994397
Recall0.784349160942739
F-score0.783716317082029
SupportNone
7

Precision:0.7960524150259277
Recall0.7956273571963373
F-score0.7952814934229506
SupportNone
8

Precision:0.7861691011341667
Recall0.7855363769746969
F-score0.784561610923163
SupportNone
9

Precision:0.8033315445641748
Recall0.8019298782047406
F-score0.8018729757711102
SupportNone
10

Precision:0.7938357997230534
Recall0.7915762929410834
F-score0.791059624086429
SupportNone
11

Precision:0.7918944928714167
Recall0.789791305288

In [152]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(Xtrain,ytrain)
pred = knn.predict(Xtest)
print(classification_report(ytest,pred))
print(confusion_matrix(ytest,pred))

             precision    recall  f1-score   support

          0       0.90      0.91      0.90       130
          1       0.71      0.75      0.73       112
          2       0.69      0.72      0.70       119
          3       0.91      0.83      0.87       139

avg / total       0.81      0.81      0.81       500

[[118  12   0   0]
 [ 13  84  15   0]
 [  0  22  86  11]
 [  0   0  24 115]]


In [153]:
predx = knn.predict(Xtrain)
print(classification_report(ytrain,predx))

             precision    recall  f1-score   support

          0       0.89      0.92      0.91       370
          1       0.79      0.82      0.80       388
          2       0.77      0.75      0.76       381
          3       0.88      0.85      0.86       361

avg / total       0.83      0.83      0.83      1500



In [121]:
dftest = pd.read_csv('test.csv')
dftest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
id               1000 non-null int64
battery_power    1000 non-null int64
blue             1000 non-null int64
clock_speed      1000 non-null float64
dual_sim         1000 non-null int64
fc               1000 non-null int64
four_g           1000 non-null int64
int_memory       1000 non-null int64
m_dep            1000 non-null float64
mobile_wt        1000 non-null int64
n_cores          1000 non-null int64
pc               1000 non-null int64
px_height        1000 non-null int64
px_width         1000 non-null int64
ram              1000 non-null int64
sc_h             1000 non-null int64
sc_w             1000 non-null int64
talk_time        1000 non-null int64
three_g          1000 non-null int64
touch_screen     1000 non-null int64
wifi             1000 non-null int64
dtypes: float64(2), int64(19)
memory usage: 164.1 KB


In [122]:
Xt = dftest.drop(columns=['id','clock_speed','mobile_wt','touch_screen']).values
Xt.shape

(1000, 17)

In [123]:
knn.predict(Xt)

ValueError: query data dimension must match training data dimension

In [11]:
X.shape[0]

2000